### ISSUE TITLE
Token alignment in sequence

### ISSUE THREAD

**Issue by songmzhang** [Nicolas-BZRD/llm-recipes#3] opened 2024-03-31 07:10 UTC
Hi, may I ask that whether you have aligned the tokens in student sequences and teacher sequences when calculating the ULD loss?

**Comment by unknowed-ER** [comment] 2024-06-25 06:57
Hello,

I am not the original author of the article, but I would like to discuss this issue with you. Cross-tokenizer alignment consists of two parts:
1. Sequence length discrepancies due to differences in tokenization granularity. The code provided by the original author does not appear to address this alignment, leading to potential inconsistencies between the optimization directions of the CE loss and ULD loss during training.
2. Inconsistencies due to different tokenizer ids. The original code aligns the teacher and student model logits by sorting them in descending order (as mentioned in Section 3.3 of the paper). However, this approach does not seem to ensure token consistency during distillation, especially when there is a significant performance gap between the teacher and student models.

In my code generation experiments (from CodeQwen-7B to stable-code-3B), I even found that the distillation method proposed by the author performed worse than SeqKD (Sequence Knowledge Distillation). I am not sure if there is an issue with my code, although I have checked it multiple times. Have you conducted any related experiments? Or, do you know of other cross-tokenizer distillation methods? I look forward to your response!

**Comment by Nicolas-BZRD** [comment] 2024-06-25 09:43
Hello everyone, sorry for my late response. I was away and completely forgot to get back to you. Thanks for your comments; you raised some very good points:

@songmzhang, actually, the ULD loss doesn't align the loss token by token. This is an issue we are actively working on. Currently, the distillation with ULD loss can be seen as a distillation over the confidence of the model across the entire sentence. For example, the student model will match the confidence of the teacher model at the beginning, and if this confidence decreases at the end, it indicates that the teacher is unsure about that part of the answer and the student model will be aware of that. I can add that we plan to release a new version in the next two months with an alignment technique and a Hugging Face wrapper to easily reproduce and enable fast iteration of your models.

@unknowed-ER: As explained above, we didn't align tokens in the v1 of the ULD Loss, but we are actively working on a second version that will be released in the next two months and will address this issue.

Regarding your first point, the distillation can currently be seen as the distillation of the teacher model's confidence to the student model for the whole sentence, not word by word. However, the larger the misalignment, the worse the results are. We notably observed this in the summary task (cf. paper table), where the gap between a non-distilled model and a distilled one shows the smallest increase. Additionally, we noticed that for small models on hard tasks (such as reasoning, math, code, and summary), distillation does not seem to be as efficient as we hoped. Notably, distillation of an opt-350m model with a Llama model yields worse performance than classical fine-tuning methods. This could be because we are trying to distill reasoning that a smaller model cannot "understand" compared to a larger one.

Concerning the second point, "_However, this approach does not seem to ensure token consistency during distillation, especially when there is a significant performance gap between the teacher and student models._" We added a cross-entropy term to our ULD Loss to ensure that the student model will at least reproduce the teacher's generation, as is done with classical fine-tuning methods. This should ensure that our techniques at least achieve the same performance as regular ones. Could you provide your code so we can discuss it together and see if something is wrong?

Actually, your use case, code distillation, is the worst scenario for our ULD Loss. You are in a setup where the model needs a lot of reasoning, and where the tokenizer can split code very differently from one model to another. I believe the next version of the ULD Loss could resolve some issues with your task and our HuggingFace wrapper make training process straightforward.

**Comment by unknowed-ER** [comment] 2024-06-25 10:54
Thank you for your response, and I'm eagerly looking forward to the next outstanding version!

Regarding the performance being lower than SeqKL: I regret to say that due to institutional restrictions, I'm unable to share my code. Instead, I'd like to provide more experimental details to offer further reference. The distilled data used the dataset from https://huggingface.co/datasets/Vezora/Tested-143k-Python-Alpaca, with a random 9:1 split for training and validation sets. The student model's performance was evaluated based on the perplexity (PPL) of correct responses generated on the validation set, with a batch size of 128 during training. I conducted hyperparameter search for distil_factor in {0, 0.1, 0.5, 1, 1.5} and found that as distil_factor decreases, the model's performance gradually improves, until distil_factor=0, which is equivalent to SeqKL.

Regarding better tokenizer alignment, I've been experimenting with model fusion techniques that implement dynamic programming [1] and minimum edit distance [2] to map two different tokenizers. I hope this information is helpful to you.

Best regards!

References:
[1] Specializing Smaller Language Models towards Multi-Step Reasoning (ICML 2023)
[2] Pack of LLMs: Model Fusion at Test-Time via Perplexity Optimization

**Comment by songmzhang** [comment] 2024-06-26 05:24
> Thank you for your response, and I'm eagerly looking forward to the next outstanding version!
> 
> Regarding the performance being lower than SeqKL: I regret to say that due to institutional restrictions, I'm unable to share my code. Instead, I'd like to provide more experimental details to offer further reference. The distilled data used the dataset from https://huggingface.co/datasets/Vezora/Tested-143k-Python-Alpaca, with a random 9:1 split for training and validation sets. The student model's performance was evaluated based on the perplexity (PPL) of correct responses generated on the validation set, with a batch size of 128 during training. I conducted hyperparameter search for distil_factor in {0, 0.1, 0.5, 1, 1.5} and found that as distil_factor decreases, the model's performance gradually improves, until distil_factor=0, which is equivalent to SeqKL.
> 
> Regarding better tokenizer alignment, I've been experimenting with model fusion techniques that implement dynamic programming [1] and minimum edit distance [2] to map two different tokenizers. I hope this information is helpful to you.
> 
> Best regards!
> 
> References: [1] Specializing Smaller Language Models towards Multi-Step Reasoning (ICML 2023) [2] Pack of LLMs: Model Fusion at Test-Time via Perplexity Optimization

Hi~, we've just released a related paper on arxiv, named "[Dual-Space Knowledge Distillation for Large Language Models](https://arxiv.org/abs/2406.17328)". And the code is also released [here](https://github.com/songmzhang/DSKD).

Specifically, we propose a dual-space kd framework to unify the prediction head of the teacher model and the student model, which can make sure that the student distribution and the teacher distribution have the same shape.
Moreover, we propose a cross-model attention mechanism to align the tokens in teacher sequences and student sequences, so that the student distribution and the teacher distribution will be well-aligned at each token position.

Therefore, our method supports all existing divergence-based functions in the vanilla KD framework, e.g., KL divergence and reverse KL divergence.

BTW, we also re-implemented the min-edit-distance method in [FuseLLM](https://arxiv.org/abs/2401.10491) and universal logit distillation in our experiments. Please refer to our paper for more details~

**Comment by unknowed-ER** [comment] 2024-06-26 07:47
> > 感谢您的回复，我热切期待下一个出色的版本！
> > 关于性能不如SeqKL：很遗憾由于机构限制，我无法分享我的代码，但我希望提供更多实验细节，以便大家参考。提炼的数据使用了https://huggingface.co/datasets/Vezora/Tested-143k-Python-Alpaca的数据集，训练集和验证集随机按9:1分割。学生模型的性能评估依据是验证集上正确答案的困惑度（PPL），训练时batch size为128。我在{0, 0.1, 0.5, 1, 1.5}中对distil_factor进行了超参数搜索，发现随着distil_factor的减小，模型性能逐渐提升，直至distil_factor=0，与SeqKL相当。
> > 关于更好地对齐标记器，我一直在尝试使用模型融合技术，这些技术可以实现动态规划 [1] 和最小编辑距离 [2] 来映射两个不同的标记器。希望这些信息对您有所帮助。
> > 此致！
> > 参考文献：[1] 专门针对多步推理的小型语言模型 (ICML 2023) [2] LLM 包：通过困惑度优化在测试时进行模型融合
> 
> 嗨~，我们刚刚在arxiv上发布了一篇相关的论文，名为“[大型语言模型的双空间知识蒸馏](https://arxiv.org/abs/2406.17328)”。代码也发布[在这里](https://github.com/songmzhang/DSKD)。
> 
> 具体来说，我们提出了一个双空间 kd 框架来统一教师模型和学生模型的预测头，这可以确保学生分布和教师分布具有相同的形状。 此外，我们提出了一种跨模型注意力机制来对齐教师序列和学生序列中的 token，以便学生分布和教师分布在每个 token 位置上都能很好地对齐。
> 
> 因此，我们的方法支持 vanilla KD 框架中所有现有的基于散度的函数，例如 KL 散度和逆 KL 散度。
> 
> 顺便说一句，我们还在实验中重新实现了[FuseLLM](https://arxiv.org/abs/2401.10491)中的最小编辑距离方法和通用逻辑蒸馏。有关更多详细信息，请参阅我们的论文~

Thank you for your open source. Exciting work!

**Comment by Nicolas-BZRD** [comment] 2024-06-26 13:59
@unknowed-ER Thanks! We will definitely try some experimentation on your use case to provide more relevant feedback and obtain the best possible results for the next paper. If you have any new questions or feedback to give do not hesitate to reopen the issue 😉

@songmzhang Congrats, good paper! I just finished reading it 🙌

**Closed as completed by Nicolas-BZRD** 2024-06-26 13:59 UTC
